# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: d:/system/system_ability_2018/system_ability_2018/ip_repo/RGB565/edit_RGB565_v1_0.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
# IP: The module: 'fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/system/system_ability_2018/system_ability_2018/ip_repo/RGB565/edit_RGB565_v1_0.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/system/system_ability_2018/system_ability_2018/ip_repo/RGB565/edit_RGB565_v1_0.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/system/system_ability_2018/system_ability_2018/ip_repo/RGB565/edit_RGB565_v1_0.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: d:/system/system_ability_2018/system_ability_2018/ip_repo/RGB565/edit_RGB565_v1_0.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0.xci
# IP: The module: 'fifo_generator_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/system/system_ability_2018/system_ability_2018/ip_repo/RGB565/edit_RGB565_v1_0.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/system/system_ability_2018/system_ability_2018/ip_repo/RGB565/edit_RGB565_v1_0.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0/fifo_generator_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/system/system_ability_2018/system_ability_2018/ip_repo/RGB565/edit_RGB565_v1_0.srcs/sources_1/ip/fifo_generator_0/fifo_generator_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_generator_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
