# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/system/system_ability_2018/system_ability_2018/ip_repo/car_by_li/edit_Motor_driver_v1_0.cache/wt [current_project]
set_property parent.project_path D:/system/system_ability_2018/system_ability_2018/ip_repo/car_by_li/edit_Motor_driver_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/system/system_ability_2018/system_ability_2018/ip_repo/car_by_li/motor_driver_1.0
  d:/system/system_ability_2018/system_ability_2018/ip_repo/Users/84397/Desktop/material/car20181216/system_ability_2018/ip_repo/Motor_driver/Motor_driver_1.0
  d:/system/system_ability_2018/system_ability_2018/ip_repo/Users/84397/Desktop/material/car20181216/system_ability_2018/ip_repo/PWM_car/PWM_car_1.0
  d:/system/system_ability_2018/system_ability_2018/ip_repo/Users/84397/Desktop/material/car20181216/system_ability_2018/ip_repo/PWM_w_Int_1.0
  d:/system/system_ability_2018/system_ability_2018/ip_repo/Users/84397/Desktop/material/car20181216/system_ability_2018/ip_repo/my_mips_packaged
} [current_project]
read_verilog -library xil_defaultlib {
  D:/system/system_ability_2018/system_ability_2018/ip_repo/car_by_li/edit_Motor_driver_v1_0.srcs/sources_1/new/pwmcar.v
  D:/system/system_ability_2018/system_ability_2018/ip_repo/car_by_li/motor_driver_1.0/hdl/Motor_driver_v1_0_S00_AXI.v
  D:/system/system_ability_2018/system_ability_2018/ip_repo/car_by_li/edit_Motor_driver_v1_0.srcs/sources_1/new/Car_speed_direciton.v
  D:/system/system_ability_2018/system_ability_2018/ip_repo/car_by_li/motor_driver_1.0/hdl/Motor_driver_v1_0.v
}
synth_design -top Motor_driver_v1_0 -part xc7a100tcsg324-1
write_checkpoint -noxdef Motor_driver_v1_0.dcp
catch { report_utilization -file Motor_driver_v1_0_utilization_synth.rpt -pb Motor_driver_v1_0_utilization_synth.pb }
