# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.cache/wt [current_project]
set_property parent.project_path C:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  c:/Users/84397/Desktop/system_ability_20181227/ip_repo/RGB565_1.0
  c:/Users/84397/Desktop/system_ability_20181227/ip_repo/car_by_li
  c:/Users/84397/Desktop/system_ability_20181227/ip_repo/PWM_w_Int_1.0
  c:/Users/84397/Desktop/system_ability_20181227/ip_repo/my_mips_packaged
} [current_project]
add_files C:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/new/ram_init.coe
add_files C:/Users/84397/Desktop/ram_init_os.coe
add_files C:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/MIPSfpga_system.bd
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_xbar_0/MIPSfpga_system_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_0_0/MIPSfpga_system_axi_gpio_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_0_0/MIPSfpga_system_axi_gpio_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_gpio_0_0/MIPSfpga_system_axi_gpio_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_blk_mem_gen_0_0/MIPSfpga_system_blk_mem_gen_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_bram_ctrl_0_0/MIPSfpga_system_axi_bram_ctrl_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_clk_wiz_0_0/MIPSfpga_system_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_clk_wiz_0_0/MIPSfpga_system_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_clk_wiz_0_0/MIPSfpga_system_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_0_0/MIPSfpga_system_axi_uart16550_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_0_0/MIPSfpga_system_axi_uart16550_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_0_0/MIPSfpga_system_axi_uart16550_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/constraints/MIPSfpga_system_mig_7series_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_mig_7series_0_0/MIPSfpga_system_mig_7series_0_0/user_design/constraints/MIPSfpga_system_mig_7series_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_intc_0_0/MIPSfpga_system_axi_intc_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_intc_0_0/MIPSfpga_system_axi_intc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_intc_0_0/MIPSfpga_system_axi_intc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_1_0/MIPSfpga_system_axi_uart16550_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_1_0/MIPSfpga_system_axi_uart16550_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_uart16550_1_0/MIPSfpga_system_axi_uart16550_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_iic_0_0/MIPSfpga_system_axi_iic_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_axi_iic_0_0/MIPSfpga_system_axi_iic_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_ila_0_0/ila_v5_1/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_ila_0_0/MIPSfpga_system_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_ahblite_axi_bridge_0_0_1/MIPSfpga_system_ahblite_axi_bridge_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_0/MIPSfpga_system_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_0/MIPSfpga_system_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_0/MIPSfpga_system_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_1/MIPSfpga_system_auto_ds_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_1/MIPSfpga_system_auto_ds_1_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_2/MIPSfpga_system_auto_ds_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_2/MIPSfpga_system_auto_ds_2_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_1/MIPSfpga_system_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_cc_0/MIPSfpga_system_auto_cc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_cc_0/MIPSfpga_system_auto_cc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_3/MIPSfpga_system_auto_ds_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_3/MIPSfpga_system_auto_ds_3_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_2/MIPSfpga_system_auto_pc_2_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_4/MIPSfpga_system_auto_ds_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_4/MIPSfpga_system_auto_ds_4_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_3/MIPSfpga_system_auto_pc_3_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_5/MIPSfpga_system_auto_ds_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_5/MIPSfpga_system_auto_ds_5_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_4/MIPSfpga_system_auto_pc_4_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_6/MIPSfpga_system_auto_ds_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_6/MIPSfpga_system_auto_ds_6_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_5/MIPSfpga_system_auto_pc_5_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_7/MIPSfpga_system_auto_ds_7_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_ds_7/MIPSfpga_system_auto_ds_7_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_pc_6/MIPSfpga_system_auto_pc_6_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_us_0/MIPSfpga_system_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/ip/MIPSfpga_system_auto_us_0/MIPSfpga_system_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all C:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/MIPSfpga_system_ooc.xdc]
set_property is_locked true [get_files C:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/MIPSfpga_system.bd]

read_verilog -library xil_defaultlib C:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/sources_1/bd/MIPSfpga_system/hdl/MIPSfpga_system_wrapper.v
read_xdc C:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/constrs_1/new/MIPSfpga_system.xdc
set_property used_in_implementation false [get_files C:/Users/84397/Desktop/system_ability_20181227/MIPSfpga_axi4_ddr/MIPSfpga_axi4.srcs/constrs_1/new/MIPSfpga_system.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top MIPSfpga_system_wrapper -part xc7a100tcsg324-1
write_checkpoint -noxdef MIPSfpga_system_wrapper.dcp
catch { report_utilization -file MIPSfpga_system_wrapper_utilization_synth.rpt -pb MIPSfpga_system_wrapper_utilization_synth.pb }
