# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {HDL-1065} -limit 10000
create_project -in_memory -part xc7a100tcsg324-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir d:/system/system_ability_2018/system_ability_2018/ip_repo/pwm_car/edit_PWM_car_v1_0.cache/wt [current_project]
set_property parent.project_path d:/system/system_ability_2018/system_ability_2018/ip_repo/pwm_car/edit_PWM_car_v1_0.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_repo_paths {
  d:/system/system_ability_2018/system_ability_2018/ip_repo/PWM_car/PWM_car_1.0
  d:/system/system_ability_2018/system_ability_2018/ip_repo/carPWM/PWM_1.0
  d:/system/system_ability_2018/system_ability_2018/my_ip_repo/PWM_w_1.0
  d:/system/system_ability_2018/system_ability_2018/ip_repo/PWM_w_Int_1.0
  d:/system/system_ability_2018/system_ability_2018/ip_repo/my_mips_packaged
} [current_project]
read_verilog -library xil_defaultlib {
  d:/system/system_ability_2018/system_ability_2018/ip_repo/pwm_car/edit_PWM_car_v1_0.srcs/sources_1/new/PWM_CAR_Controller.v
  d:/system/system_ability_2018/system_ability_2018/ip_repo/pwm_car/pwm_car_1.0/hdl/PWM_car_v1_0_S00_AXI.v
  d:/system/system_ability_2018/system_ability_2018/ip_repo/pwm_car/edit_PWM_car_v1_0.srcs/sources_1/new/PWM_Speed_Controller.v
  d:/system/system_ability_2018/system_ability_2018/ip_repo/pwm_car/pwm_car_1.0/hdl/PWM_car_v1_0.v
}
synth_design -top PWM_car_v1_0 -part xc7a100tcsg324-1
write_checkpoint -noxdef PWM_car_v1_0.dcp
catch { report_utilization -file PWM_car_v1_0_utilization_synth.rpt -pb PWM_car_v1_0_utilization_synth.pb }
